name: CI

on:
  - push
  - pull_request

jobs:
  cargo_test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clipboard dependencies
        # https://github.com/aweinstock314/rust-clipboard/blob/07d080be58a361a5bbdb548fafe9449843d968be/README.md#prerequisites
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: cargo tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '-- --test-threads 1'

      - name: codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  e2e_test:
    name: End-to-End Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clipboard dependencies
        # https://github.com/aweinstock314/rust-clipboard/blob/07d080be58a361a5bbdb548fafe9449843d968be/README.md#prerequisites
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: e2e tests
        run: make test

  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clipboard dependencies
        # https://github.com/aweinstock314/rust-clipboard/blob/07d080be58a361a5bbdb548fafe9449843d968be/README.md#prerequisites
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
